package sketch:embedded@0.0.0;

interface lcd {
    use delay.{delay};
    use i2c.{i2c};

    write: func(connection: i2c, delay: delay, message: string);
}

interface hts {
    use i2c.{i2c};

    get-temperature: func(connection: i2c) -> result<string, u16>;
    get-humidity: func(connection: i2c) -> result<string, u16>;
}

world connection {
    import i2c;
}

world sensor {
    include connection;

    export hts;
}

world screen {
    import delay;
    include connection;

    export lcd;
}