package my:project;

interface types {
    i2c-init: func(address: u8) -> result<u32, u32>;
    write: func(message: string) -> result<u32, u32>;
}

world i2c-app {
    import types;

    export start: func() -> result;
}
