package sketch:implementation;
    
world sensor {
    import wasi:i2c/i2c@0.1.0;

    export hts: interface {
        use wasi:i2c/i2c@0.1.0.{i2c, error-code};

        get-temperature: func(connection: i2c) -> result<string, error-code>;
        get-humidity: func(connection: i2c) -> result<string, error-code>;
    }
}