package component:app;

interface device {
    use types.{regular-file};

    record i2c {
        bus: u8,
        i2cdev: regular-file,
        address: u16,
    }

    new: func() -> result<i2c, u32>;
}

interface lcd {
    setup: func();
    write: func(message: string);
}

world connection {
    import wasi:filesystem/filesystem;

    export device;
}

world screen {
    // The host needs to provide a device
    import device;

    export lcd;
}

world app {
    import lcd;
}
