[workspace]
members = ["lcd", "hat", "segment_led"]
resolver = "2"

[workspace.dependencies]
lol_alloc = "0.4.1"
bitflags = "2.5.0"
wit-bindgen-rt = { version = "0.22.0", default-features = false }
compiler_builtins = { version = "0.1.108", features = ["mem"] }
